[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = stm32cube
monitor_speed = 115200
build_flags = 
    -Iinclude
    -Ilib/FreeRTOS/include
    -Ilib/FreeRTOS/portable/GCC/ARM_CM3
lib_deps = 
    file://lib/FreeRTOS
lib_ldf_mode = deep+
lib_compat_mode = off